// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbptellkgbbasxnhqkex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZicHRlbGxrZ2JiYXN4bmhxa2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjA4MjcsImV4cCI6MjA3MjI5NjgyN30.W2J3MXcAUW7nm0Y9rJeDLDvrtV1R-6adtTFQzwHQCVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});